### ISSUE TITLE
[sdk] Cryptovoxels SDK script has issues loading images and external urls dynamically

### ISSUE THREAD

**Issue by JSeam2** [zestymarket/sdk#116]
Right now the cryptovoxels sdk does not dynamically update the image textures, changing the URL field programmatically from the code does not change the image.
![unknown](https://user-images.githubusercontent.com/22354889/158644706-f5767c30-ebc2-425f-ab4b-360999384217.png)

Link to space [Anoncat's Clubhouse Link](https://www.cryptovoxels.com/play?coords=S@1447E,1212S)
Right now, I have manually appended links from the campaign to the space hence things are showing up.

This is likely because cryptovoxels now caches the image textures using a service at `https://compressor.cryptovoxels.com/compressed?` before allowing the textures to be rendered on the site itself. It also appears the cryptovoxels only allows the endpoint to be called from the cryptovoxels webapp itself. 

I have dropped a message in the Cryptovoxels' Discord asking for help around this. It appears that this issue can only be handled with the help of the Cryptovoxels team at the moment. Would appreciate if anyone else has other ideas and workarounds about this.

For now the Cryptovoxels SDK on Zesty Market is not working.

**Comment by msub2** [comment]
@JSeam2 this is fixed now, isn't it?

**Comment by JSeam2** [comment]
@msub2 yes this is fixed in #126 closing for now
