### ISSUE TITLE
Explore different options for hosting IPFS assets

### ISSUE THREAD

**Issue by limbofeather** [zestymarket/sdk#149]
Currently the existing https://ipfs.io gateway can be slow to load assets. Perhaps we can explore a solution like Filebase?

**Comment by limbofeather** [comment]
![Uploading image.png…]()

**Comment by JSeam2** [comment]
Proposed solution
1. Filebase as the default endpoint
2. Fallback to public IPFS endpoints should Filebase fail

This approach should allow for sufficient redundancy in the SDK

**Comment by JSeam2** [comment]
Addressed in #152.

To reopen if any more issues arise.
