### ISSUE TITLE
[sdk] Check for `ipfs.io` links, they are all being rate throttled. Need to check with pinata regarding ipns status.

### ISSUE THREAD

**Issue by JSeam2** [zestymarket/sdk#59]

**Comment by JSeam2** [comment]
utils/formats.js

unity/Assets/ZestySDK/Scripts/Utils/Formats.cs

assets/default-variant.json

uses ipfs.io links, this needs to be changed

**Comment by msub2** [comment]
Could we just keep a list of different gateways and select randomly from that list?

**Comment by JSeam2** [comment]
There's https://ipfs.github.io/public-gateway-checker/

They all have rate limits though, I think the random selection is a temporary hack. Will need to pester pinata.cloud to provide ipns for the dedicated gateway
